import type { WizardConfig } from "../helper/wizardSpec.ts";

/**
 * Defines the mode of the adapter, which determines how the generated Vega specification will be integrated with the existing specification in the editor.
 * - `template`: The generated specification will replace the existing specification in the editor.
 * - `append`: The generated specification will be merged with the existing specification in the editor, allowing for multiple charts to be created in the same specification.
 */
export type AdapterMode = 'template' | 'append';

/**
 * Defines the structure of a field in the wizard form.
 */
export interface WizardField {
    /**
     * Unique identifier for the field, used as the key in the form values.
     */
    name: string;
    /**
     * Label for the field to be displayed in the form UI.
     */
    label: string;
    /**
     * The type of the field, which determines how it will be rendered in the form and how the value will be processed.
     */
    type: 'string' | 'number' | 'boolean' | 'color';
    /**
     * Indicates whether the field is required to be filled out by the user.
     */
    required?: boolean;
    /**
     * Default value for the field, which will be used if the user does not provide a value.
     */
    defaultValue?: string | number | boolean;
}

/**
 * Defines the structure of the Vega specification that will be generated by the wizard adapter.
 * This is a flexible interface that can include any valid Vega specification properties, but it also includes some common properties for convenience.
 */
export interface WizardSpec {
    $schema?: string;
    description?: string;
    width?: number;
    height?: number;
    padding?: number;
    autosize?: string;
    data?: Record<string, unknown>[];
    signals?: Record<string, unknown>[];
    scales?: Record<string, unknown>[];
    axes?: Record<string, unknown>[];
    marks?: Record<string, unknown>[];
    legends?: Record<string, unknown>[];
    [key: string]: unknown;
}

/**
 * Interface for the wizard adapter, which is responsible for providing the necessary fields for the wizard form and generating the Vega specification based on the input in the wizard.
 */
export interface WizardAdapter {
    /**
     * The mode of the adapter, see {@link AdapterMode}.
     */
    mode: AdapterMode;
    /**
     * Returns fields that should be displayed in the wizard form for the specific chart type that the adapter is responsible for.
     * @return An array of {@link WizardField} objects that define the fields for the wizard form.
     */
    getFields(): WizardField[];

    /**
     * Generates a Vega specification based on the provided {@link WizardConfig}.
     * @param config - The configuration for the wizard.
     * @return A Vega specification object that can be merged with the existing specification in the editor based on the adapter's mode.
     */
    getSpec(config: WizardConfig): WizardSpec;
}