import type { WizardAdapter } from "../adapters/WizardAdapter.ts";
import { BarVerticalAdapter } from "../adapters/template/BarVerticalAdapter.ts";
import { BarHorizontalAdapter } from "../adapters/template/BarHorizontalAdapter.ts";
import { PieAdapter } from "../adapters/template/PieAdapter.ts";
import { ScatterAdapter } from "../adapters/template/ScatterAdapter.ts";
import { RectAdapter } from "../adapters/append/RectAdapter.ts";
import { gui4VegaLogger } from "../../../logger.ts";

/**
 * Supported chart types for the wizard and their corresponding adapters.
 */
export type ChartType = 'barVertical' | 'barHorizontal' | 'pie' | 'scatter' | 'rect';

/**
 * Configuration object for the wizard.
 */
export interface WizardConfig {
    /**
     * The type of chart to be generated.
     */
    chartType: ChartType;
    /**
     * The name of the dataset from the Vega specification to be used for the chart.
     */
    datasetName: string;
    /**
     * Field mappings where the key is the adapter field name and the value is the corresponding dataset field name selected by the user in the wizard.
     */
    fields: Record<string, string>;
}

/**
 * Mapping of chart types to their corresponding {@link WizardAdapter} instances.
 * Each adapter is responsible for generating the appropriate Vega specification based on the provided {@link WizardConfig}.
 */
export const adapters: Record<ChartType, WizardAdapter> = {
    barVertical: new BarVerticalAdapter(),
    barHorizontal: new BarHorizontalAdapter(),
    pie: new PieAdapter(),
    scatter: new ScatterAdapter(),
    rect: new RectAdapter()
};

/**
 * Generates a new Vega specification by merging the current specification with the new specification generated by the appropriate adapter based on the provided {@link WizardConfig}.
 * The merging strategy depends on the adapter's mode (append or prepend).
 * @param currentCode - The current Vega specification in JSON string format.
 * @param config - The configuration for the wizard, including the selected chart type, dataset name, and field mappings.
 * @return A new Vega specification in JSON string format that includes the changes based on the wizard configuration.
 */
export function generateSpec(currentCode: string, config: WizardConfig): string {
    try {
        // Parse the current Vega specification from the editor
        const currentSpec = JSON.parse(currentCode);

        // Get the adapter for the selected chart type
        const adapter = adapters[config.chartType];

        // If no adapter is found for the selected chart type, return the current code without changes
        if (!adapter) return currentCode;

        // Generate the new Vega specification based on the wizard configuration using the adapter
        const newSpec = adapter.getSpec(config);

        // Append mode, merge new spec with current spec and return
        if (adapter.mode === 'append') {
            const merged = { ...currentSpec };

            if (newSpec.data) {
                merged.data = merged.data ? [...merged.data, ...newSpec.data] : [...newSpec.data];
            }
            if (newSpec.signals) {
                merged.signals = merged.signals ? [...merged.signals, ...newSpec.signals] : [...newSpec.signals];
            }
            if (newSpec.scales) {
                merged.scales = merged.scales ? [...merged.scales, ...newSpec.scales] : [...newSpec.scales];
            }
            if (newSpec.axes) {
                merged.axes = merged.axes ? [...merged.axes, ...newSpec.axes] : [...newSpec.axes];
            }
            if (newSpec.marks) {
                merged.marks = merged.marks ? [...merged.marks, ...newSpec.marks] : [...newSpec.marks];
            }
            if (newSpec.legends) {
                merged.legends = merged.legends ? [...merged.legends, ...newSpec.legends] : [...newSpec.legends];
            }

            return JSON.stringify(merged, null, 2);
        }

        // Template mode, merge only data and signals
        // Prepend data
        if (currentSpec.data) {
             newSpec.data = newSpec.data ? [...currentSpec.data, ...newSpec.data] : [...currentSpec.data];
        }

        // Prepend signals
        if (currentSpec.signals) {
            newSpec.signals = newSpec.signals ? [...currentSpec.signals, ...newSpec.signals] : [...currentSpec.signals];
        }

        return JSON.stringify(newSpec, null, 2);

    } catch (e) {
        gui4VegaLogger.error("Error generating spec", e);
        return currentCode;
    }
}