name: Deploy Node.js Package to GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: gui4vega_react
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@teemo6'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy-docs:
    needs: publish-gpr
    uses: ./.github/workflows/docs.yml
    permissions:
      contents: read
      pages: write
      id-token: write